name: audio_graph
description: Highly customizable audio playback plugin for flutter ios/android. For more details, see the README
version: 0.0.6
homepage: https://github.com/SKKbySSK/audio_graph

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: work.ksprogram.audio_graph
        pluginClass: AudioGraphPlugin
      ios:
        package: work.ksprogram.audio_graph
        pluginClass: AudioGraphPlugin
