name: audio_graph
description: Flutter plugin to build custom audio graph.
version: 0.0.4
homepage: https://github.com/SKKbySSK/audio_graph

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: work.ksprogram.audio_graph
        pluginClass: AudioGraphPlugin
      ios:
        package: work.ksprogram.audio_graph
        pluginClass: AudioGraphPlugin
